# name, category, price, description
DEMO_MENU = [
    ('Espresso', 'Coffee', 65, 'A short, rich shot with a golden crema. Deep cocoa notes and a clean finish.'),
    ('Americano', 'Coffee', 70, 'Our signature espresso, lengthened with hot water. Smooth, balanced, and beautifully simple.'),
    ('Iced Americano', 'Coffee', 75, 'Bright espresso poured over cool water and ice. A crisp start to any afternoon.'),
    ('Cafe Latte', 'Coffee', 85, 'Rich espresso meets silky milk. A mellow, comforting cup with notes of chocolate and toasted nuts.'),
    ('Iced Latte', 'Coffee', 90, 'Fresh espresso and creamy milk over ice. Your everyday pick-me-up, made a little cooler.'),
    ('Cappuccino', 'Coffee', 85, 'Espresso, steamed milk, and a generous layer of airy foam. A classic with a soft finish.'),
    ('Mocha', 'Coffee', 95, 'Bold espresso with dark cocoa and milk. Chocolate comfort in every sip.'),
    ('Caramel Macchiato', 'Coffee', 105, 'Vanilla milk, espresso, and a finishing drizzle of caramel. Sweet, smooth, and layered.'),
    ('Cold Brew', 'Coffee', 110, 'Slow-steeped coffee served over ice. Naturally smooth, with a gentle sweetness.'),
    ('Dirty Coffee', 'Coffee', 110, 'Warm espresso poured over chilled milk. Two delicious layers, best enjoyed right away.'),
    ('Classic Cocoa', 'Non-Coffee', 85, 'Deep chocolate and creamy milk. A comforting favorite, with or without the chill.'),
    ('Matcha Latte', 'Non-Coffee', 95, 'Earthy matcha whisked smooth and paired with milk. A quietly vibrant daily ritual.'),
    ('Strawberry Milk', 'Non-Coffee', 85, 'A little berry brightness with fresh milk. Fruity, creamy, and easy to love.'),
    ('Vanilla Milk', 'Non-Coffee', 80, 'Milk with a soft touch of vanilla. Sometimes simple is all you need.'),
    ('Thai Tea', 'Tea', 75, 'Aromatic Thai tea blended with creamy milk. Bold, fragrant, and familiar.'),
    ('Lemon Tea', 'Tea', 70, 'Fresh tea lifted with a squeeze of lemon. Bright citrus and a clean, refreshing finish.'),
    ('Peach Tea', 'Tea', 80, 'Mellow tea with sunny peach notes. A light, fruity break in your day.'),
    ('Matcha Lemon', 'Tea', 90, 'Green matcha meets lively lemon. A refreshing balance of earthiness and citrus.'),
    ('Butter Croissant', 'Bakery', 75, 'Golden, flaky layers with a soft buttery center. Made for your morning coffee.'),
    ('Chocolate Croissant', 'Bakery', 85, 'Buttery pastry wrapped around a rich chocolate center. A small moment of indulgence.'),
    ('Blueberry Muffin', 'Bakery', 70, 'A tender muffin filled with blueberries. Soft crumb, golden top, everyday happiness.'),
    ('Chocolate Brownie', 'Bakery', 80, 'A rich chocolate square with a delicate crust and a soft, fudgy middle.'),
    ('Basque Cheesecake', 'Dessert', 120, 'A deeply caramelized top and a creamy, delicate center. Beautifully simple cheesecake.'),
    ('Tiramisu', 'Dessert', 130, 'Coffee-soaked layers and mascarpone cream, finished with a dusting of cocoa.'),
    ('Chocolate Cake', 'Dessert', 110, 'Layers of chocolate sponge and smooth chocolate cream. For a sweeter kind of break.'),
    ('Ham & Cheese Sandwich', 'Breakfast', 120, 'Toasted bread, savory ham, and melted cheese. A satisfying bite any time of day.'),
    ('Egg Toast', 'Breakfast', 95, 'Golden toast topped with an egg. A warm, simple breakfast to start things right.'),
    ('Breakfast Set', 'Breakfast', 169, 'Eggs, toast, and a savory side. A slow-morning favorite, all on one plate.'),
]
